- hosts: all
  connection: local
  become: true


  tasks:

    - set_fact:
        ansible_python_interpreter: /usr/bin/python3
  
    - name: Sprawdzanie systemu
      fail: msg="System operacyjny jest starszy od Ubuntu 18"
      when: ansible_distribution != "Ubuntu" and ansible_distribution_major_version | int < 18


#   - import_tasks: repo.yml
#     tags: repo 

    - import_tasks: pakiety.yml
      tags: pakiety
 
    - name: Informacja
      debug:
        msg: "Aktualizacja programu zostala zakonczona."